"""`crossweft agents` -- the repository carries its own agent harness.

A repository that adopts crossweft must not depend on each developer installing
a plugin: any coding agent that opens it should pick the seams up as part of the
architecture. `crossweft agents` writes, idempotently and never over someone
else's text:

- `AGENTS.md`: a marked block with the working rules. Codex, Copilot, Cursor and
  Claude Code read AGENTS.md (Claude Code directly when there is no CLAUDE.md,
  .claude/CLAUDE.md or CLAUDE.local.md; otherwise through an `@AGENTS.md`
  import, which is added to the first of those files that exists);
- `.claude/settings.json`: the SessionStart, PostToolUse and Stop hooks, merged
  into whatever the file already holds (a group that also holds someone
  else's hook is never changed: ours gets a group of its own);
- `.claude/skills/crossweft/SKILL.md`: the working skill (fix, attest, map a
  repository from scratch), copied from the installed package.

How the hooks start crossweft is declared once, as `agent.command` in
crossweft.json (default `crossweft`; `agents --command` and `init --command`
record it). With `"agent": {"harness": true}` (`init` and `agents` set it),
`crossweft check` fails when any of these is missing or out of date, or when a
hook is not exactly `<agent.command> hook claude-code <event>`: the harness is
part of the architecture and is guarded like any other seam.

Every file is written atomically, in the line endings it already uses.

This module depends on nothing else in crossweft, so the engine can call it.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path

CONFIG_FILE = "crossweft.json"   # engine.CONFIG_FILE; this module imports nothing from it
SKILL_SOURCE = Path(__file__).resolve().parent / "skills" / "crossweft" / "SKILL.md"
SKILL_TARGET = ".claude/skills/crossweft/SKILL.md"
SETTINGS = ".claude/settings.json"
BLOCK_BEGIN = "<!-- crossweft-agents:begin (generated by `crossweft agents`; re-run it to update) -->"
BLOCK_END = "<!-- crossweft-agents:end -->"
# the markers of any version, where `agents` writes them: at the start of a line
# (the same text quoted inside a sentence is someone's prose, not a block)
BEGIN_LINE = re.compile(r"^<!-- crossweft-agents:begin", re.MULTILINE)
END_LINE = re.compile("^" + re.escape(BLOCK_END), re.MULTILINE)
SKILL_MARKER = ("<!-- generated by `crossweft agents` from the installed crossweft package; "
                "run it again to update, do not edit -->")
DEFAULT_COMMAND = "crossweft"
EDIT_MATCHER = "Edit|Write|MultiEdit|NotebookEdit"
EVENTS = (("SessionStart", "session-start", None, 30),
          ("PostToolUse", "post-edit", EDIT_MATCHER, 60),
          ("Stop", "stop", None, 120))
# Any of these makes Claude Code read the CLAUDE.md files instead of AGENTS.md
# (https://code.claude.com/docs/en/memory#agents-md), so one of them must
# import it; `agents` adds the import to the first one that exists.
CLAUDE_FILES = (("CLAUDE.md", "@AGENTS.md"), (".claude/CLAUDE.md", "@../AGENTS.md"),
                ("CLAUDE.local.md", "@AGENTS.md"))
# Whether the project's hooks run is proved by running `<agent.command> --version`
# in the shell Claude Code uses; crossweft answers in well under a second, and the
# plugin's shortest hook timeout is 30s.
LAUNCHER_PROBE_TIMEOUT = 10
VERSION_ANSWER = re.compile(r"^crossweft \d", re.MULTILINE)   # argparse's `--version` line


class HarnessError(Exception):
    """A file the harness must change is unreadable or belongs to someone else."""


class HarnessWriteError(HarnessError):
    """Writing failed part-way; the message says what was already written."""


def agents_block(model_dir: str) -> str:
    return f"""{BLOCK_BEGIN}
## Component seams (crossweft)

This repository keeps a map of its components and of every place where two of
them must agree -- routes, headers, protocol versions, DTO fields, env vars,
pipe names, duplicated algorithms -- in `{model_dir}`, and `crossweft check`
verifies the map against the code. Agents write and maintain the map, and
the check makes sure it cannot drift from the code.

- Before editing a file another component depends on, run
  `crossweft impact <path>`: it names the file on the other side and the guard
  that compares them. Change both sides.
- Before you finish, `crossweft check` must print `RESULT: PASS`. For Claude
  Code the hooks in `.claude/settings.json` do this for you: after each edit
  they name the other side, and they send you back while a seam disagrees.
- When you add a component, a connection, or a value two places must share,
  put it on the map in the same change: a block, a link with anchors and
  `contract.enforcement`, and a guard that reads both sides for every
  hand-written seam (`crossweft discover` suggests guards). The `crossweft`
  skill has the full procedure, including mapping a repository from scratch.
- Never weaken a guard, widen a regex, or add an `allow` entry or a finding
  just to make the check pass; each needs a concrete reason.
{BLOCK_END}
"""


def skill_text() -> str:
    source = SKILL_SOURCE.read_text(encoding="utf-8")
    if not source.startswith("---\n"):
        raise HarnessError(f"{SKILL_SOURCE} has no front matter")
    end = source.index("\n---\n", 4) + len("\n---\n")
    return source[:end] + SKILL_MARKER + "\n" + source[end:]


def hook_command(command: str, event: str) -> str:
    return f"{command} hook claude-code {event}"


def configured_command(root: Path) -> str:
    """`agent.command` in crossweft.json -- how the hooks start crossweft, the
    one value `agents` writes into them and `check` compares them with."""
    agent = _read_json(root / CONFIG_FILE).get("agent", {})
    command = agent.get("command", DEFAULT_COMMAND) if isinstance(agent, dict) else None
    if not isinstance(command, str) or not command.strip():
        raise HarnessError(f"{CONFIG_FILE}: agent.command must be a non-empty string")
    return command.strip()


def _launcher(command: object, event: str) -> str | None:
    """`<launcher>` of a hook command shaped like the ones `agents` writes
    (`<launcher> hook claude-code <event>`), else None."""
    suffix = f" hook claude-code {event}"
    if not isinstance(command, str) or not command.strip().endswith(suffix):
        return None
    return command.strip()[:-len(suffix)].strip() or None


# --------------------------------------------------------------------------- #
# files: UTF-8, their own line endings, replaced atomically
# --------------------------------------------------------------------------- #

def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        raise HarnessError(f"{path} is not UTF-8 text ({exc.reason} at byte {exc.start}) -- "
                           "convert it to UTF-8") from exc
    except OSError as exc:
        raise HarnessError(f"{path}: {exc}") from exc


def _read_json(path: Path, text: str | None = None) -> dict:
    try:
        data = json.loads(_read_text(path) if text is None else text)
    except ValueError as exc:
        raise HarnessError(f"{path} is not valid JSON ({exc}) -- fix it first") from exc
    if not isinstance(data, dict):
        raise HarnessError(f"{path} must hold a JSON object")
    return data


def _json_indent(text: str) -> int | str:
    """The indentation a JSON file already uses (2 for a new or flat one)."""
    match = re.search(r"^([ \t]+)\S", text, re.MULTILINE)
    if not match:
        return 2
    whitespace = match.group(1)
    return len(whitespace) if set(whitespace) == {" "} else whitespace   # tabs: as they are


def _read_only(path: Path) -> bool:
    return path.is_file() and not os.access(path, os.W_OK)


def write_text(path: Path, text: str) -> None:
    """Replace `path` with `text` (LF line breaks) through a temporary file in the
    same directory and os.replace: an interrupted write leaves the old file,
    never half of the new one. The file keeps its line endings (CRLF or LF)
    and its permissions; a new file gets LF and the usual permissions. A
    symlink stays a link (its target is replaced); a read-only file is an
    error, as a plain write would be."""
    if path.is_symlink():
        path = path.resolve()
    if _read_only(path):
        raise PermissionError(f"{path} is read-only")
    existing = path.is_file()
    newline = "\r\n" if existing and b"\r\n" in path.read_bytes() else "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.{os.getpid()}.crossweft-tmp")
    try:
        with open(temp, "wb") as handle:
            handle.write(text.replace("\n", newline).encode("utf-8"))
        if existing:
            os.chmod(temp, path.stat().st_mode & 0o7777)
        os.replace(temp, path)
    except BaseException:
        try:
            temp.unlink(missing_ok=True)   # our own temporary file, never the target
        except OSError:
            pass   # the error being raised says more than a failed cleanup
        raise


# --------------------------------------------------------------------------- #
# .claude/settings.json
# --------------------------------------------------------------------------- #

def _hook_entries(settings: dict, name: str) -> list:
    hooks = settings.get("hooks", {})
    groups = hooks.get(name, []) if isinstance(hooks, dict) else []
    return groups if isinstance(groups, list) else []


def _candidates(settings: dict) -> dict[str, list[tuple[dict, dict, str]]]:
    """Per hook event: every (group, hook, launcher) shaped like a crossweft hook."""
    found: dict[str, list[tuple[dict, dict, str]]] = {}
    for name, event, _, _ in EVENTS:
        found[name] = []
        for group in _hook_entries(settings, name):
            if not isinstance(group, dict) or not isinstance(group.get("hooks"), list):
                continue
            for hook in group["hooks"]:
                launcher = _launcher(hook.get("command"), event) if isinstance(hook, dict) \
                    else None
                if launcher:
                    found[name].append((group, hook, launcher))
    return found


def _shared_launchers(found: dict) -> set[str]:
    """Launchers that start the hook of every event: a complete set an earlier
    `agents` wrote, which `agents` may rewrite to the current command. (Whether
    a launcher starts crossweft is not decided here: `check` compares with the
    declared agent.command, the plugin asks the launcher itself.)"""
    return set.intersection(*({launcher for _, _, launcher in found[name]}
                              for name, _, _, _ in EVENTS))


_PLAIN_MATCHER = re.compile(r"[A-Za-z0-9_\- ,|]*")


def _matches(matcher: object, tool: str) -> bool:
    """Claude Code's matcher rules (https://code.claude.com/docs/en/hooks#matcher):
    "*", "" or no matcher match every tool; letters, digits, _ - space , and |
    only are exact tool names separated by | or ,; anything else is a regular
    expression."""
    if matcher is None or matcher in ("", "*"):
        return True
    if not isinstance(matcher, str):
        return False
    if _PLAIN_MATCHER.fullmatch(matcher):
        return tool in {part.strip() for part in re.split(r"[|,]", matcher)}
    try:
        return re.search(matcher, tool) is not None
    except re.error:
        return False   # a pattern Python cannot read counts as not matching: reported


def _matches_edits(group: dict) -> bool:
    return all(_matches(group.get("matcher"), tool) for tool in ("Edit", "Write"))


def _hook_problems(settings: dict, command: str) -> list[tuple[str, str]]:
    """(key, message) for what keeps the hooks from starting `command`, the
    declared agent.command, at each event."""
    fix = "run `crossweft agents`"
    found_problems: list[tuple[str, str]] = []
    if settings.get("disableAllHooks") is True:
        found_problems.append(("agents:hooks", f'{SETTINGS} sets "disableAllHooks": true, so '
                               "none of the seam hooks runs -- remove it (`crossweft agents` "
                               "does not change it)"))
    found = _candidates(settings)
    for name, event, matcher, _ in EVENTS:
        wanted = hook_command(command, event)
        ours = [group for group, hook, _ in found[name] if hook["command"].strip() == wanted]
        if not ours:
            others = sorted({hook["command"].strip() for _, hook, _ in found[name]})
            seen = f" (it runs {', '.join(f'`{c}`' for c in others)})" if others else ""
            found_problems.append((f"agents:hooks:{event}", f"{SETTINGS} has no {name} hook "
                                   f"running `{wanted}`{seen}, and {CONFIG_FILE} declares "
                                   f"agent.command `{command}` -- {fix} (with --command if "
                                   "crossweft starts another way here)"))
        elif matcher and not any(_matches_edits(group) for group in ours):
            found_problems.append((f"agents:hooks:{event}", f"the crossweft {name} hook does "
                                   f"not match Edit and Write, so edits go unreported -- {fix}"))
    return found_problems


def project_hooks_run(root: Path, cwd: Path) -> bool:
    """True when the project's own settings run all three crossweft hooks AND
    they would start crossweft here, so the plugin can stay quiet. Configured is
    not enough: a plugin-only user has no `crossweft` on PATH (the project hook
    fails with 127), and `echo` or `true` hooks check nothing -- a quiet plugin
    would let drift through."""
    path = root / SETTINGS
    if not path.is_file():
        return False
    started = os.environ.get("CLAUDE_PROJECT_DIR")
    if started and Path(started).resolve() != root.resolve():
        # Claude Code reads .claude/settings.json from the directory the session
        # started in (https://code.claude.com/docs/en/settings), not from ours
        return False
    try:
        settings = _read_json(path)
        command = configured_command(root)
    except HarnessError:
        return False
    return not _hook_problems(settings, command) and _answers_as_crossweft(command, root, cwd)


def _hook_shell() -> str | None:
    """The shell Claude Code runs hook commands in. bin/crossweft (how the plugin
    starts) exports the bash running it as CROSSWEFT_SHELL; otherwise bash from
    PATH on Windows (Git Bash -- never WSL's System32 bash, another system) and
    sh elsewhere (https://code.claude.com/docs/en/hooks). None: nothing to ask."""
    shell = os.environ.get("CROSSWEFT_SHELL")
    if shell:
        return shell
    if os.name == "nt":
        bash = shutil.which("bash")
        return bash if bash and "system32" not in bash.lower() else None
    return shutil.which("sh")


def _answers_as_crossweft(command: str, root: Path, cwd: Path) -> bool:
    """Run `<command> --version` as Claude Code would run the hook -- its shell
    (quoting, $CLAUDE_PROJECT_DIR), the hook's working directory, without the
    plugin's own variables -- and require crossweft's answer. A program that is
    missing, `echo`, `true`, a module that is not runnable, or no shell to ask:
    the project's hooks do not run crossweft."""
    shell = _hook_shell()
    if not shell:
        return False
    env = {key: value for key, value in os.environ.items()
           if not key.startswith("CLAUDE_PLUGIN_")}
    env.setdefault("CLAUDE_PROJECT_DIR", str(root))
    try:
        probe = subprocess.run([shell, "-c", f"{command} --version"], cwd=cwd, env=env,
                               stdin=subprocess.DEVNULL, capture_output=True,
                               timeout=LAUNCHER_PROBE_TIMEOUT)
    except (OSError, subprocess.TimeoutExpired):
        return False
    return probe.returncode == 0 and bool(
        VERSION_ANSWER.search(probe.stdout.decode("utf-8", errors="replace")))


def _merge_settings(settings: dict, command: str) -> list[str]:
    """Merge the three hooks, each started by `command`, into `settings`."""
    changes = []
    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise HarnessError(f"{SETTINGS}: 'hooks' must be an object")
    found = _candidates(settings)
    shared = _shared_launchers(found)

    def installed(launcher: str) -> bool:
        # an earlier run's: it names crossweft, or it starts the hook of every
        # event (a complete set written with a custom --command). Hooks merely
        # shaped like ours, even at two events, belong to another tool.
        return "crossweft" in launcher or launcher in shared

    for name, event, matcher, timeout in EVENTS:
        wanted = hook_command(command, event)
        ours = [(group, hook) for group, hook, launcher in found[name]
                if hook["command"] == wanted or installed(launcher)]
        for group, hook in ours:
            if hook["command"] != wanted:
                hook["command"] = wanted
                changes.append(f"{SETTINGS}: {name} hook now runs `{wanted}`")
        if ours and (not matcher or any(_matches_edits(group) for group, _ in ours)):
            continue
        # a group that holds only our hook is ours to fix; a shared one is not
        own = [group for group, _ in ours
               if all(any(hook is mine for _, mine in ours) for hook in group["hooks"])]
        if own:
            own[0]["matcher"] = matcher
            changes.append(f"{SETTINGS}: {name} matcher set to {matcher}")
            continue
        group = {"hooks": [{"type": "command", "command": wanted, "timeout": timeout}]}
        if matcher:
            group = {"matcher": matcher, **group}
        groups = hooks.setdefault(name, [])
        if not isinstance(groups, list):
            raise HarnessError(f"{SETTINGS}: hooks.{name} must be a list")
        groups.append(group)
        changes.append(f"{SETTINGS}: added the {name} hook (`{wanted}`)")
    return changes


def _with_block(text: str, block: str) -> str:
    """`text` with one crossweft block, the current one, where the first block
    was. Every marked block is crossweft's own text, so extra ones go."""
    spans = []
    begin = BEGIN_LINE.search(text)
    while begin:
        end_marker = END_LINE.search(text, begin.start())
        if not end_marker:
            raise HarnessError("AGENTS.md has a crossweft block without its end marker -- "
                               f"restore `{BLOCK_END}` or delete the block")
        end = end_marker.end()
        if text[end:end + 1] == "\n":
            end += 1
        spans.append((begin.start(), end))
        begin = BEGIN_LINE.search(text, end)
    if not spans:
        return block if not text else text.rstrip("\n") + "\n\n" + block
    kept = [text[end:nxt] for (_, end), (nxt, _) in zip(spans, spans[1:])]
    return text[:spans[0][0]] + block + "".join(kept) + text[spans[-1][1]:]


def _claude_files(root: Path) -> list[tuple[Path, str]]:
    """The files that make Claude Code read CLAUDE.md files instead of AGENTS.md,
    with the import line each would need. Empty: Claude Code reads AGENTS.md."""
    return [(root / rel, line) for rel, line in CLAUDE_FILES if (root / rel).is_file()]


def _imports_agents(text: str) -> bool:
    return any(line.strip().startswith(("@AGENTS.md", "@./AGENTS.md", "@../AGENTS.md"))
               for line in text.splitlines())


def _brings_agents(path: Path, text: str, root: Path) -> bool:
    """Does this CLAUDE file give Claude Code the AGENTS.md rules: it imports
    AGENTS.md, or it is AGENTS.md (a symlink to it)?"""
    return _imports_agents(text) or path.resolve() == (root / "AGENTS.md").resolve()


def install(root: Path, model_dir: str, command: str = DEFAULT_COMMAND,
            dry_run: bool = False) -> list[str]:
    """Write the harness; returns what changed. `command` is how the hooks start
    crossweft -- the caller records it as agent.command. Raises HarnessError,
    writing nothing, when a file it must change is not valid, not its own or
    read-only, and HarnessWriteError, naming what was written, when a write
    fails."""
    writes: dict[Path, str] = {}
    changes: list[str] = []

    settings_path = root / SETTINGS
    raw_settings = _read_text(settings_path) if settings_path.is_file() else ""
    settings = _read_json(settings_path, raw_settings) if settings_path.is_file() else {}
    before = json.dumps(settings, sort_keys=True)
    changes += _merge_settings(settings, command)
    if json.dumps(settings, sort_keys=True) != before or not settings_path.is_file():
        writes[settings_path] = json.dumps(settings, indent=_json_indent(raw_settings),
                                           ensure_ascii=False) + "\n"

    agents_path = root / "AGENTS.md"
    old = _read_text(agents_path) if agents_path.is_file() else ""
    new = _with_block(old, agents_block(model_dir))
    if new != old:
        writes[agents_path] = new
        blocks = len(BEGIN_LINE.findall(old))
        if not agents_path.exists():
            changes.append("AGENTS.md: created")
        elif blocks > 1:
            changes.append("AGENTS.md: kept one crossweft block, the current one")
        elif blocks:
            changes.append("AGENTS.md: updated the crossweft block")
        else:
            changes.append("AGENTS.md: added the crossweft block")

    claude = [(path, line, _read_text(path)) for path, line in _claude_files(root)]
    if claude and not any(_brings_agents(path, text, root) for path, _, text in claude):
        path, line, text = claude[0]
        names = ", ".join(p.relative_to(root).as_posix() for p, _, _ in claude)
        writes[path] = text.rstrip("\n") + f"\n\n{line}\n"
        changes.append(f"{path.relative_to(root).as_posix()}: added `{line}` (with {names} "
                       "present, Claude Code reads the CLAUDE.md files instead of AGENTS.md)")

    skill_path = root / SKILL_TARGET
    wanted = skill_text()
    if skill_path.is_file():
        current = _read_text(skill_path)
        if SKILL_MARKER not in current:
            raise HarnessError(f"{SKILL_TARGET} exists and was not generated by crossweft -- "
                               "move it away or rename the skill, then run again")
        if current != wanted:
            writes[skill_path] = wanted
            changes.append(f"{SKILL_TARGET}: updated")
    else:
        writes[skill_path] = wanted
        changes.append(f"{SKILL_TARGET}: created")

    read_only = [path.relative_to(root).as_posix() for path in writes if _read_only(path)]
    if read_only:
        raise HarnessError(f"{', '.join(read_only)} must change but is read-only -- make it "
                           "writable, then run again")
    if not dry_run:
        written: list[str] = []
        for path, text in writes.items():
            rel = path.relative_to(root).as_posix()
            try:
                write_text(path, text)
            except OSError as exc:
                raise HarnessWriteError(
                    f"could not write {rel} ({exc}); " + (
                        f"already written: {', '.join(written)}" if written
                        else "nothing was written") + " -- fix the cause and run it again"
                ) from exc
            written.append(rel)
    return changes


def problems(root: Path, model_dir: str) -> list[tuple[str, str, str]]:
    """(key, message, path) for every part of the harness that is missing or
    stale. Used by `crossweft check` when agent.harness is true."""
    fix = "run `crossweft agents`"
    found: list[tuple[str, str, str]] = []
    settings_path = root / SETTINGS
    if not settings_path.is_file():
        found.append(("agents:hooks", f"{SETTINGS} is missing, so Claude Code sessions run "
                                      f"without the seam hooks -- {fix}", SETTINGS))
    else:
        try:
            settings = _read_json(settings_path)
            command = configured_command(root)
        except HarnessError as exc:
            found.append(("agents:hooks", f"{exc} -- the seam hooks cannot run", SETTINGS))
        else:
            found += [(key, message, SETTINGS)
                      for key, message in _hook_problems(settings, command)]

    agents_path = root / "AGENTS.md"
    try:
        text = _read_text(agents_path) if agents_path.is_file() else ""
    except HarnessError as exc:
        found.append(("agents:agents-md", f"{exc} -- the crossweft block cannot be read",
                      "AGENTS.md"))
    else:
        blocks = len(BEGIN_LINE.findall(text))
        if blocks > 1:
            found.append(("agents:agents-md", f"AGENTS.md has {blocks} crossweft blocks and "
                          f"agents read every one -- {fix} (it keeps the current one)",
                          "AGENTS.md"))
        elif agents_block(model_dir) not in text:
            state = "is out of date" if blocks else "is missing"
            found.append(("agents:agents-md", f"the crossweft block in AGENTS.md {state} -- "
                          f"{fix}", "AGENTS.md"))

    claude = _claude_files(root)
    if claude:
        rel = claude[0][0].relative_to(root).as_posix()
        try:
            imported = any(_brings_agents(path, _read_text(path), root) for path, _ in claude)
        except HarnessError as exc:
            found.append(("agents:claude-md", f"{exc} -- cannot tell whether it imports "
                          "AGENTS.md", rel))
        else:
            if not imported:
                names = ", ".join(path.relative_to(root).as_posix() for path, _ in claude)
                found.append(("agents:claude-md", f"with {names} present Claude Code reads the "
                              "CLAUDE.md files instead of AGENTS.md, and none of them imports "
                              f"it -- add `{claude[0][1]}` to {rel} or {fix}", rel))

    skill_path = root / SKILL_TARGET
    if not skill_path.is_file():
        found.append(("agents:skill", f"{SKILL_TARGET} is missing -- {fix}", SKILL_TARGET))
    else:
        try:
            stale = _read_text(skill_path) != skill_text()
        except HarnessError as exc:
            found.append(("agents:skill", f"{exc} -- {fix}", SKILL_TARGET))
        else:
            if stale:
                found.append(("agents:skill", f"{SKILL_TARGET} differs from the installed "
                              f"crossweft's skill -- {fix}", SKILL_TARGET))
    return found
