"""Strings for the generated documents and the HTML viewer.

One table per language, identical key sets (the self-test asserts it), so a
missing translation is caught before it renders as a raw key. Add a language by
copying the "en" table and translating every value.
"""

from __future__ import annotations

EN = {
    "status": {"current": "current", "planned": "planned", "out-of-scope": "out of scope",
               "test-only": "test only", "legacy": "legacy"},
    "evidence": {"none": "not proven", "source": "source", "ci": "CI",
                 "runtime": "installed product"},
    "severity": {"blocker": "blocker", "major": "major", "minor": "minor", "info": "info"},
    "fstatus": {"open": "open", "accepted": "accepted with reason", "closed": "closed"},
    "transport": {
        "named-pipe": "named pipe", "https": "HTTPS", "http-loopback": "HTTP localhost",
        "process-launch": "process launch", "file": "file", "registry": "registry", "scm": "SCM",
        "in-process": "in-process call", "generated-code": "generated code",
        "build-input": "build input", "embedded": "embedded", "git": "git", "tunnel": "tunnel",
        "smtp": "SMTP", "sql": "SQL", "object-store": "object store", "cache": "cache",
        "webhook": "webhook", "oauth": "OAuth", "manual": "manual (operator)", "ui": "UI",
        "mtls": "mTLS", "dpapi": "DPAPI", "docker": "docker", "os-api": "OS API", "ssh": "SSH",
    },
    "kind": {"actor": "person", "executable": "program", "service": "service",
             "component": "component", "library": "library", "store": "store",
             "external": "external service", "artifact": "artifact", "tool": "tool",
             "contract": "contract", "site": "site", "host": "host", "ci": "CI", "group": "group"},
    "data_kind": {"credential": "credential", "key": "key", "config": "configuration",
                  "artifact": "artifact", "payload": "payload", "state": "state",
                  "identity": "identity", "policy": "policy", "message": "message",
                  "image": "image", "evidence": "evidence", "telemetry": "telemetry",
                  "code": "code", "account": "account"},
    "text": {
        "generated": "> Generated by `crossweft render` from [`{model}`]({model_link}). Do not "
                     "edit this file by hand: change the model and render again. Checked against "
                     "the code by `crossweft check`.",
        "verified": "> The model was last verified against commit `{sha}` ({date}). Evidence "
                    "\"source\" means the code says so, not that an installed product was tested.",
        "intro": "The map answers four questions: **which blocks exist**, **who talks to whom and "
                 "how**, **who waits for what** and **where each piece of data comes from**. "
                 "Everything is written once in the model and checked against the code, so "
                 "mismatches are found automatically.",
        "viewer_bullet": "- **[Interactive map](viewer.html)** — open `viewer.html` in a "
                         "browser: click a block to see its links, waits and data.",
        "pages_bullet": "- [Blocks](blocks.md) · [Flows — who waits for what](flows.md) · "
                        "[Data — where it comes from](data.md) · [Findings](findings.md)",
        "how_to_read": "How to read",
        "term": "Term", "meaning": "Meaning",
        "term_block": "Block", "term_block_d": "A program, service, component, store, external "
                      "service or build tool. A block lives in a lane and has a status.",
        "term_link": "Link", "term_link_d": "Who passes what to whom: the transport (pipe, HTTPS, "
                     "file, generated code...), the contract and where it is defined, what the "
                     "caller waits for, what happens on error.",
        "term_flow": "Flow", "term_flow_d": "Ordered steps over links: who calls whom and what "
                     "each step waits for.",
        "term_data": "Data", "term_data_d": "Keys, receipts, payloads, states: who creates them, "
                     "which links carry them, where they are stored, where the format is defined.",
        "term_finding": "Finding", "term_finding_d": "A recorded mismatch between two sides, the "
                        "code or the docs. Each has an owner and a next step.",
        "term_contract": "Link contract", "term_contract_d": "How the two sides of a link stay in "
                         "agreement: one owner (`shared-code`, `generated`, `schema-tests` — "
                         "named in `defined_in`) or hand-written on both sides (`duplicated`, "
                         "`convention`, `none`) — then a join, set or pair must read both sides, "
                         "or a change to one side silently leaves the other behind.",
        "statuses": "Statuses", "evidence_label": "Evidence",
        "overview": "Overview",
        "not_current": "Not in the current system",
        "not_current_d": "These blocks exist in the repository but are not part of the current "
                         "system (legacy, planned or out of scope). Their links to current blocks "
                         "are a common source of confusion.",
        "block": "Block", "status_col": "Status", "lane": "Lane", "what_it_is": "What it is",
        "blocks_by_lane": "Blocks by lane", "does": "What it does", "talks_to": "Talks to",
        "flows_heading": "Flows — who waits for what",
        "findings_heading": "Findings",
        "findings_count": "Open or accepted: **{open}** (closed: {closed}). Full register with "
                          "evidence: [findings.md](findings.md).",
        "id": "ID", "severity_col": "Severity", "summary_col": "Summary", "next_step": "Next step",
        "owner": "Owner",
        "update_heading": "How to update the map",
        "update_1": "1. You change a seam in code (a route, pipe, contract, file, key) — in the "
                    "same change, update the matching `{model}/*.json` (block, link, data or flow).",
        "update_2": "2. Before committing, run `crossweft impact` (or `crossweft impact --base "
                    "origin/main` for a whole branch): which links run through the changed files, "
                    "where the other side of each is, and what guards it. Re-read the other side "
                    "of every touched seam.",
        "update_3": "3. `crossweft check` verifies code anchors, values on both sides, routes, "
                    "data provenance, seam contracts, statuses and the findings register.",
        "update_4": "4. `crossweft render` regenerates these pages and `viewer.html`.",
        "update_5": "5. Found a mismatch you cannot fix now? Record a finding with an owner, a "
                    "next step and the detector key; when it is fixed, the check itself asks you "
                    "to close the record.",
        "update_6": "6. `crossweft show <id>` prints one block, link or data item with its "
                    "neighbours.",
        "composition": "Model: {blocks} blocks, {links} links, {flows} flows, {data} data items, "
                       "{joins} value guards, {sets} set guards, {pairs} paired regions, "
                       "{findings} findings.",
        "contracts_line": "Contracts of current links: {items} (`compiler` — a call inside one "
                          "binary; `--` — the link has no second side in our code).",
        "blocks_title": "Blocks and links",
        "blocks_intro": "Each block: what it does, who it talks to (outgoing and incoming links), "
                        "what it waits for, which data it creates and receives. Nested blocks are "
                        "internal components.",
        "f_status": "status", "f_kind": "kind", "f_lane": "lane", "f_runs": "runs on",
        "f_owner": "owner", "f_evidence": "evidence", "f_parent": "part of", "f_code": "code",
        "f_docs": "docs", "f_requirements": "requirements", "f_inside": "inside",
        "sends": "**Sends / calls:**", "receives": "**Receives / is called by:**",
        "col_peer": "With", "col_what": "What and how", "col_contract": "Contract",
        "col_waits": "Who waits for what", "col_error": "On error", "col_data": "Data",
        "waits_before": "**Waits for, before it works:**", "if_missing": "if missing",
        "creates_data": "creates data", "gets_data": "receives data",
        "findings_label": "findings", "anchors_in_code": "Anchors in code",
        "more": "... {n} more",
        "flows_title": "Flows — who waits for what",
        "flows_intro": "Each flow is a sequence of steps over the links of the map. Every step "
                       "says who calls whom, what the caller waits for and what happens next.",
        "f_trigger": "trigger", "f_result": "result",
        "col_no": "#", "col_who": "Who -> whom", "col_action": "Action", "col_wait": "Waits",
        "col_then": "Then", "waits_note": "waits — {w}",
        "data_title": "Data — where it comes from",
        "data_intro": "For each kind of data: who creates it, which links carry it, who receives "
                      "it, where it is stored and where its format is defined. `check` requires "
                      "that data leaves a block only if the block created it or received it over "
                      "another link of the map.",
        "col_data_name": "Data", "col_kind": "Kind", "col_created": "Created by",
        "col_carried": "Carried over", "col_received": "Received by", "col_stored": "Stored",
        "f_created": "created by", "f_sensitivity": "sensitivity", "also_in": "also appears in",
        "format_defined": "format defined in",
        "findings_title": "Findings",
        "findings_intro": "Register of mismatches between the sides of links, the code and the "
                          "docs. A record with a detector key (`detected_by`) is reconciled "
                          "automatically: while the problem reproduces it is shown as known; once "
                          "it is fixed the check asks you to close the record.",
        "col_fkind": "Kind",
        "f_severity": "severity", "f_fkind": "kind", "f_since": "since", "f_where": "where",
        "f_impact": "impact", "f_next": "next step", "f_defer": "reason to defer",
        "f_closed": "closed", "f_detector": "detector", "f_proof": "evidence",
    },
    "ui": {
        "title": "System map", "search": "Find a block, link or data...", "search_label": "Search",
        "theme": "Light / dark theme", "plane": "Plane:", "statuses": "Statuses:",
        "expand_all": "Expand all", "collapse_all": "Collapse", "zoom": "Zoom:",
        "zoom_out": "Smaller", "zoom_fit": "Fit to width", "fit": "fit", "zoom_in": "Larger",
        "canvas": "Diagram of blocks and links",
        "tab_map": "Map", "tab_flows": "Flows — who waits for what", "tab_data": "Data — where from",
        "tab_findings": "Findings", "plane_all": "All",
        "family_pipe": "named pipe (local IPC)",
        "family_http": "network: HTTP/HTTPS, webhook, OAuth, mTLS, tunnel, SSH",
        "family_file": "files, registry, DPAPI, embedded resources",
        "family_launch": "process launch, SCM, in-process call",
        "family_build": "generated code, build input, git",
        "family_store": "database, object store, cache, SMTP",
        "family_manual": "manual (operator)", "family_other": "other",
        "show_inner": "Show internal components", "anchors": "Anchors in code",
        "contract": "contract", "waits": "waits", "on_error": "on error", "sends": "sends ->",
        "gets": "<- receives", "routes": "routes", "evidence": "evidence", "runs": "runs on",
        "owner": "owner", "part_of": "part of", "code": "code", "docs": "docs",
        "requirements": "requirements", "findings": "Findings", "inside": "Inside",
        "collapse_on_map": "Collapse on the map", "expand_on_map": "Expand on the map",
        "waits_before": "Waits for, before it works", "if_missing": "If missing: ",
        "sends_calls": "Sends / calls", "receives": "Receives", "data": "Data",
        "creates": "creates", "gets_data": "receives", "in_flows": "Takes part in flows",
        "links_count": "links", "transport": "transport", "sync": "sync",
        "envs": "environments", "flow_step": "Flow: ", "step": "step",
        "wait_prefix": "waits: ", "waits_cap": "Waits: ", "then_cap": "Then: ",
        "steps": "Steps — who waits for what", "trigger": "trigger", "result": "result",
        "kind": "kind", "created_by": "created by", "carried": "carried over",
        "received_by": "received by", "stored": "stored", "sensitivity": "sensitivity",
        "also_from": "also appears in", "format": "format defined in", "severity": "severity",
        "status": "status", "where": "where", "impact": "impact", "next_step": "next step",
        "defer": "reason to defer", "closed_by": "closed", "detector": "detector",
        "proof": "evidence", "since": "since", "nothing": "Nothing selected",
        "pick": "Click a block or a link to see its details.", "no_findings": "No findings.",
        "legend": "Legend", "no_match": "Nothing matches.",
        "data_path": "Data path", "in_reply": " (in the reply)",
        "not_carried": "Not carried over any link of the map (used inside its block).",
        "ref_block": "block: ", "ref_link": "link: ", "ref_data": "data: ", "ref_flow": "flow: ",
        "dashed": "dashed — legacy / planned / out of scope", "how_to": "How to use",
        "how_to_d": "Columns are lanes: where a block runs. Arrows are links: who passes what to "
                    "whom. Click a block to see whom it talks to, what it waits for and which "
                    "data it creates or receives. The \"▸ N\" button expands internal components.",
        "n_blocks": "blocks: {n}", "n_links": "links: {n}", "n_flows": "flows: {n}",
        "n_data": "data items: {n}",
        "open_findings": "Open findings: {open} (blockers {blocker}, major {major}). Blocks and "
                         "links that have them are marked \"!\". ",
        "open_list": "Open the list", "link_colors": "Link colours", "evidence_h": "Evidence",
        "evidence_d": "\"source\" — the code exists and is checked by anchors; \"CI\" — "
                      "covered by automated checks; \"installed product\" — proven on an "
                      "installed build.",
        "flows_d": "Pick a flow: its participants and step numbers light up on the map.",
        "data_h": "Data — where it comes from",
        "data_d": "Pick a data item: its source, path and receivers light up on the map.",
        "findings_d": "Mismatches between the sides of links, the code and the docs. Click to "
                      "highlight on the map.",
        "overview": "Overview", "links_n": "links: {n}", "flow_step_n": "{name}, step {n}",
        "verified_meta": "verified against the code: {sha} · {date}",
    },
}

RU = {
    "status": {"current": "текущий", "planned": "запланирован", "out-of-scope": "вне текущего этапа",
               "test-only": "только тесты", "legacy": "наследие"},
    "evidence": {"none": "не доказано", "source": "исходник", "ci": "CI",
                 "runtime": "установленный продукт"},
    "severity": {"blocker": "блокер", "major": "серьёзно", "minor": "мелко", "info": "инфо"},
    "fstatus": {"open": "открыта", "accepted": "принята с причиной", "closed": "закрыта"},
    "transport": {
        "named-pipe": "Named Pipe", "https": "HTTPS", "http-loopback": "HTTP localhost",
        "process-launch": "запуск процесса", "file": "файл", "registry": "реестр", "scm": "SCM",
        "in-process": "вызов в процессе", "generated-code": "генерация кода",
        "build-input": "вход сборки", "embedded": "встроено", "git": "git", "tunnel": "туннель",
        "smtp": "SMTP", "sql": "SQL", "object-store": "объектное хранилище", "cache": "кэш",
        "webhook": "webhook", "oauth": "OAuth", "manual": "вручную (оператор)", "ui": "UI",
        "mtls": "mTLS", "dpapi": "DPAPI", "docker": "docker", "os-api": "API ОС", "ssh": "SSH",
    },
    "kind": {"actor": "человек", "executable": "программа", "service": "служба",
             "component": "компонент", "library": "библиотека", "store": "хранилище",
             "external": "внешний сервис", "artifact": "артефакт", "tool": "инструмент",
             "contract": "контракт", "site": "сайт", "host": "хост", "ci": "CI", "group": "группа"},
    "data_kind": {"credential": "удостоверение", "key": "ключ", "config": "конфигурация",
                  "artifact": "артефакт", "payload": "полезная нагрузка", "state": "состояние",
                  "identity": "идентичность", "policy": "политика", "message": "сообщение",
                  "image": "изображение", "evidence": "доказательство", "telemetry": "телеметрия",
                  "code": "код", "account": "аккаунт"},
    "text": {
        "generated": "> Сгенерировано командой `crossweft render` из [`{model}`]({model_link}). "
                     "Не редактируйте этот файл вручную: правьте модель и перегенерируйте. "
                     "Проверка против кода: `crossweft check`.",
        "verified": "> Модель сверена с кодом на коммите `{sha}` ({date}). Доказанность "
                    "«исходник» не означает проверку установленного продукта.",
        "intro": "Карта отвечает на четыре вопроса: **какие блоки есть**, **кто с кем и как "
                 "общается**, **кто чего ждёт** и **откуда берутся данные**. Всё записано один раз "
                 "в модели и проверяется против кода, поэтому расхождения находятся автоматически.",
        "viewer_bullet": "- **[Интерактивная схема](viewer.html)** — откройте `viewer.html` в "
                         "браузере: клик по блоку показывает его связи, ожидания и данные.",
        "pages_bullet": "- [Блоки](blocks.md) · [Сценарии — кто что ждёт](flows.md) · "
                        "[Данные — откуда берутся](data.md) · [Нестыковки](findings.md)",
        "how_to_read": "Как читать",
        "term": "Понятие", "meaning": "Что значит",
        "term_block": "Блок", "term_block_d": "Программа, служба, компонент, хранилище, внешний "
                      "сервис или инструмент сборки. У блока есть зона и статус.",
        "term_link": "Связь", "term_link_d": "Кто кому что передаёт: транспорт (pipe, HTTPS, "
                     "файл, генерация кода…), контракт и где он определён, что ждёт вызывающий, "
                     "что происходит при ошибке.",
        "term_flow": "Сценарий", "term_flow_d": "Упорядоченные шаги по связям: кто кого вызывает "
                     "и чего ждёт на каждом шаге.",
        "term_data": "Данные", "term_data_d": "Ключи, квитанции, полезные нагрузки, состояния: "
                     "кто создаёт, по каким связям идут, где хранятся, где задан формат.",
        "term_finding": "Нестыковка", "term_finding_d": "Найденное расхождение между сторонами, "
                        "кодом и документацией. У каждой — владелец и следующий шаг.",
        "term_contract": "Контракт связи", "term_contract_d": "Как две стороны связи держатся "
                         "согласованными: один владелец (`shared-code`, `generated`, "
                         "`schema-tests` — назван в `defined_in`) или ручная запись на обеих "
                         "сторонах (`duplicated`, `convention`, `none`) — тогда join, set или "
                         "pair обязан читать обе стороны, иначе обновление одной стороны молча "
                         "оставит другую позади.",
        "statuses": "Статусы", "evidence_label": "Доказанность",
        "overview": "Обзор",
        "not_current": "Не в текущем контуре",
        "not_current_d": "Эти блоки есть в репозитории, но не входят в текущую систему "
                         "(наследие, запланированное или вне текущего этапа). Их связи с текущими "
                         "блоками — частый источник путаницы.",
        "block": "Блок", "status_col": "Статус", "lane": "Зона", "what_it_is": "Что это",
        "blocks_by_lane": "Блоки по зонам", "does": "Что делает", "talks_to": "Общается с",
        "flows_heading": "Сценарии — кто что ждёт",
        "findings_heading": "Нестыковки",
        "findings_count": "Открыто или принято с причиной: **{open}** (закрыто: {closed}). "
                          "Полный реестр с доказательствами — [findings.md](findings.md).",
        "id": "ID", "severity_col": "Серьёзность", "summary_col": "Суть",
        "next_step": "Следующий шаг", "owner": "Владелец",
        "update_heading": "Как обновлять карту",
        "update_1": "1. Меняете связь в коде (маршрут, pipe, контракт, файл, ключ) — в том же "
                    "изменении поправьте `{model}/*.json` (блок, связь, данные или сценарий).",
        "update_2": "2. Перед коммитом — `crossweft impact` (или `crossweft impact --base "
                    "origin/main` для всей ветки): какие связи проходят через изменённые файлы, "
                    "где другая сторона каждой и чем шов сверяется. Перечитайте другую сторону "
                    "каждого затронутого шва.",
        "update_3": "3. `crossweft check` проверяет якоря в коде, совпадение значений на обеих "
                    "сторонах, маршруты, происхождение данных, контракты швов, статусы и реестр "
                    "нестыковок.",
        "update_4": "4. `crossweft render` перегенерирует эти страницы и `viewer.html`.",
        "update_5": "5. Нашли расхождение, которое нельзя исправить сейчас — запишите нестыковку "
                    "с владельцем, следующим шагом и ключом детектора; когда её исправят, "
                    "проверка сама потребует закрыть запись.",
        "update_6": "6. `crossweft show <id>` — блок, связь или данные с соседями.",
        "composition": "Состав модели: блоков {blocks}, связей {links}, сценариев {flows}, "
                       "данных {data}, сверок значений {joins}, сверок множеств {sets}, "
                       "парных участков {pairs}, нестыковок {findings}.",
        "contracts_line": "Контракты текущих связей: {items} (`compiler` — вызов внутри одного "
                          "бинарника; `--` — у связи нет второй стороны в нашем коде).",
        "blocks_title": "Блоки и связи",
        "blocks_intro": "Каждый блок: что делает, с кем общается (исходящие и входящие связи), "
                        "чего ждёт, какие данные создаёт и получает. Вложенные блоки — внутренние "
                        "компоненты.",
        "f_status": "статус", "f_kind": "вид", "f_lane": "зона", "f_runs": "где работает",
        "f_owner": "владелец", "f_evidence": "доказанность", "f_parent": "входит в",
        "f_code": "код", "f_docs": "документация", "f_requirements": "требования",
        "f_inside": "внутри",
        "sends": "**Отправляет / вызывает:**", "receives": "**Принимает / его вызывают:**",
        "col_peer": "С кем", "col_what": "Что и как", "col_contract": "Контракт",
        "col_waits": "Кто чего ждёт", "col_error": "При ошибке", "col_data": "Данные",
        "waits_before": "**Ждёт, прежде чем работать:**", "if_missing": "если нет",
        "creates_data": "создаёт данные", "gets_data": "получает данные",
        "findings_label": "нестыковки", "anchors_in_code": "Якоря в коде",
        "more": "… ещё {n}",
        "flows_title": "Сценарии — кто что ждёт",
        "flows_intro": "Каждый сценарий — последовательность шагов по связям карты. На каждом "
                       "шаге указано, кто кого вызывает, чего ждёт вызывающий и что происходит "
                       "дальше.",
        "f_trigger": "запуск", "f_result": "результат",
        "col_no": "№", "col_who": "Кто → кому", "col_action": "Действие", "col_wait": "Ждёт",
        "col_then": "Дальше", "waits_note": "ждёт — {w}",
        "data_title": "Данные — откуда берутся",
        "data_intro": "Для каждого вида данных: кто их создаёт, по каким связям они идут, кто "
                      "получает, где хранятся и где задан формат. Проверка `check` требует, чтобы "
                      "данные покидали блок только если он их создал или получил по другой связи "
                      "карты.",
        "col_data_name": "Данные", "col_kind": "Вид", "col_created": "Создаёт",
        "col_carried": "Идёт по связям", "col_received": "Получают", "col_stored": "Хранится",
        "f_created": "создаёт", "f_sensitivity": "чувствительность",
        "also_in": "также появляется в", "format_defined": "формат задан",
        "findings_title": "Нестыковки",
        "findings_intro": "Реестр найденных расхождений между сторонами связей, кодом и "
                          "документацией. Запись с ключом детектора (`detected_by`) сверяется "
                          "автоматически: пока проблема воспроизводится, она показывается как "
                          "известная; когда её исправят, проверка потребует закрыть запись.",
        "col_fkind": "Вид",
        "f_severity": "серьёзность", "f_fkind": "вид", "f_since": "с", "f_where": "где",
        "f_impact": "последствия", "f_next": "следующий шаг", "f_defer": "причина отложить",
        "f_closed": "закрыто", "f_detector": "детектор", "f_proof": "доказательства",
    },
    "ui": {
        "title": "Карта системы", "search": "Найти блок, связь, данные…", "search_label": "Поиск",
        "theme": "Светлая / тёмная тема", "plane": "Контур:", "statuses": "Статусы:",
        "expand_all": "Раскрыть всё", "collapse_all": "Свернуть", "zoom": "Масштаб:",
        "zoom_out": "Мельче", "zoom_fit": "Уместить по ширине", "fit": "по ширине",
        "zoom_in": "Крупнее", "canvas": "Схема блоков и связей",
        "tab_map": "Карта", "tab_flows": "Сценарии — кто что ждёт", "tab_data": "Данные — откуда",
        "tab_findings": "Нестыковки", "plane_all": "Всё",
        "family_pipe": "Named Pipe (локальный IPC)",
        "family_http": "сеть: HTTP/HTTPS, webhook, OAuth, mTLS, туннель, SSH",
        "family_file": "файлы, реестр, DPAPI, встроенные ресурсы",
        "family_launch": "запуск процесса, SCM, вызов в процессе",
        "family_build": "генерация кода, вход сборки, git",
        "family_store": "БД, объектное хранилище, кэш, SMTP",
        "family_manual": "вручную (оператор)", "family_other": "прочее",
        "show_inner": "Показать внутренние компоненты", "anchors": "Якоря в коде",
        "contract": "контракт", "waits": "ждёт", "on_error": "при ошибке", "sends": "передаёт →",
        "gets": "← получает", "routes": "маршруты", "evidence": "доказанность",
        "runs": "где работает", "owner": "владелец", "part_of": "входит в", "code": "код",
        "docs": "документация", "requirements": "требования", "findings": "Нестыковки",
        "inside": "Внутри", "collapse_on_map": "Свернуть на схеме",
        "expand_on_map": "Раскрыть на схеме", "waits_before": "Ждёт, прежде чем работать",
        "if_missing": "Если нет: ", "sends_calls": "Отправляет / вызывает",
        "receives": "Принимает", "data": "Данные", "creates": "создаёт", "gets_data": "получает",
        "in_flows": "Участвует в сценариях", "links_count": "связей", "transport": "транспорт",
        "sync": "синхронность", "envs": "окружения", "flow_step": "Сценарий: ", "step": "шаг",
        "wait_prefix": "ждёт: ", "waits_cap": "Ждёт: ", "then_cap": "Дальше: ",
        "steps": "Шаги — кто что ждёт", "trigger": "запуск", "result": "результат",
        "kind": "вид", "created_by": "создаёт", "carried": "идёт по связям",
        "received_by": "получают", "stored": "хранится", "sensitivity": "чувствительность",
        "also_from": "также появляется в", "format": "формат задан", "severity": "серьёзность",
        "status": "статус", "where": "где", "impact": "последствия", "next_step": "следующий шаг",
        "defer": "причина отложить", "closed_by": "закрыто", "detector": "детектор",
        "proof": "доказательства", "since": "с", "nothing": "Ничего не выбрано",
        "pick": "Кликните блок или связь, чтобы увидеть подробности.",
        "no_findings": "Нестыковок нет.", "legend": "Легенда", "no_match": "Ничего не найдено.",
        "data_path": "Путь данных", "in_reply": " (в ответе)",
        "not_carried": "Не передаётся по связям карты (используется внутри блока).",
        "ref_block": "блок: ", "ref_link": "связь: ", "ref_data": "данные: ",
        "ref_flow": "сценарий: ",
        "dashed": "пунктир — наследие / запланировано / вне этапа", "how_to": "Как пользоваться",
        "how_to_d": "Колонки — зоны: где работает блок. Стрелки — связи: кто кому что передаёт. "
                    "Клик по блоку показывает, с кем он общается, чего ждёт и какие данные "
                    "создаёт или получает. Кнопка «▸ N» раскрывает внутренние компоненты.",
        "n_blocks": "блоков {n}", "n_links": "связей {n}", "n_flows": "сценариев {n}",
        "n_data": "данных {n}",
        "open_findings": "Открытых нестыковок: {open} (блокеров {blocker}, серьёзных {major}). "
                         "Блоки и связи с ними отмечены «!». ",
        "open_list": "Открыть список", "link_colors": "Цвета связей", "evidence_h": "Доказанность",
        "evidence_d": "«исходник» — код есть и проверен по якорям; «CI» — покрыто "
                      "автоматическими проверками; «установленный продукт» — доказано на "
                      "установленной программе.",
        "flows_d": "Выберите сценарий: на схеме подсветятся участники и номера шагов.",
        "data_h": "Данные — откуда берутся",
        "data_d": "Выберите данные: на схеме подсветятся источник, путь и получатели.",
        "findings_d": "Расхождения между сторонами связей, кодом и документацией. Клик — "
                      "подсветка на схеме.",
        "overview": "Обзор", "links_n": "связей: {n}", "flow_step_n": "{name}, шаг {n}",
        "verified_meta": "сверено с кодом: {sha} · {date}",
    },
}

LANGUAGES = {"en": EN, "ru": RU}


def table(language: str) -> dict:
    return LANGUAGES[language]


def key_mismatches() -> list[str]:
    """Keys present in one language table but not in another (self-test)."""
    problems = []
    base = EN
    for name, other in LANGUAGES.items():
        for section, values in base.items():
            theirs = other.get(section, {})
            missing = sorted(set(values) - set(theirs))
            extra = sorted(set(theirs) - set(values))
            if missing:
                problems.append(f"{name}.{section} lacks {missing}")
            if extra:
                problems.append(f"{name}.{section} has extra {extra}")
    return problems
