"""Public Claude and Codex plugin layout regressions."""

from __future__ import annotations

import json
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SHARED_FIELDS = ("name", "version", "homepage", "repository", "license", "keywords")


def read_json(relative: str) -> dict:
    return json.loads((REPO / relative).read_text(encoding="utf-8"))


class PluginPackagingTests(unittest.TestCase):
    def test_claude_and_codex_manifests_share_public_metadata(self) -> None:
        claude = read_json(".claude-plugin/plugin.json")
        codex = read_json(".codex-plugin/plugin.json")

        for field in SHARED_FIELDS:
            self.assertEqual(codex[field], claude[field], field)
        self.assertEqual(codex["author"], claude["author"])
        self.assertIn("Crossweft", claude["description"])
        self.assertIn("explicit Crossweft commands", codex["description"])
        self.assertEqual(claude["skills"], ["./crossweft/skills/"])
        self.assertEqual(codex["skills"], "./crossweft/skills/")
        self.assertTrue((REPO / codex["skills"]).is_dir())

    def test_codex_plugin_is_a_skill_integration_without_unverified_hooks(self) -> None:
        codex = read_json(".codex-plugin/plugin.json")
        self.assertNotIn("hooks", codex)
        self.assertEqual(codex["interface"]["capabilities"], ["Read"])

    def test_codex_marketplace_points_to_the_public_repository(self) -> None:
        marketplace = read_json(".agents/plugins/marketplace.json")
        self.assertEqual(marketplace["name"], "crossweft")
        self.assertEqual(marketplace["interface"]["displayName"], "Crossweft Plugins")
        self.assertEqual(marketplace["plugins"], [{
            "name": "crossweft",
            "source": {
                "source": "url",
                "url": "https://github.com/happyin-app/crossweft.git",
            },
            "policy": {"installation": "AVAILABLE", "authentication": "ON_INSTALL"},
            "category": "Developer Tools",
        }])

    def test_generated_claude_skills_match_the_packaged_skill(self) -> None:
        source = (REPO / "crossweft/skills/crossweft/SKILL.md").read_text(encoding="utf-8")
        marker = ("<!-- generated by `crossweft agents` from the installed crossweft package; "
                  "run it again to update, do not edit -->")
        front_matter_end = source.index("\n---\n", 4) + len("\n---\n")
        expected = source[:front_matter_end] + marker + "\n" + source[front_matter_end:]

        for relative in (
            ".claude/skills/crossweft/SKILL.md",
            "examples/polyglot-shop/.claude/skills/crossweft/SKILL.md",
        ):
            self.assertEqual((REPO / relative).read_text(encoding="utf-8"), expected, relative)


if __name__ == "__main__":
    unittest.main()
